### ISSUE TITLE
Password requests window keeps popping on wrong password

### ISSUE THREAD

**Issue by Binoya** [lppedd/j#5]
I am traying to use your library and I found that when you create a JConnection with a password that is wrong the window for the password keeps popping on. This seems to be connected to calling `as400.setGuiAvailable(false);` [after trying to create the as400 object](https://github.com/lppedd/j/blob/5b9f5e475f7558eea29319b649a6a41aab285590/src/lppedd/j/api/JConnection.java#L67).
Kindly do the needful to resolve this problem, my start up businness depends on this library!!

**Comment by lppedd** [comment]
@Binoya hi! I coded this little library to make it easier to accomplish some tasks at my past workplace (years ago). I really haven't access to an IBM i machine right now. However why don't you fork this repo and try to edit it?
I still remember how JTOpen works so I'm open to questions ;)

```
as400.setGuiAvailable(false); 
```
is perfectly fine as there should be no windows pop-ups AFAIK (per documentation).
The only thing it is done inside the `AS400` constructor is
```
credVault_ = new PasswordVault(password);
```
